// Daily lines for the home screen. One is picked per day; "Another" cycles through them.
// k = concept / title, t = the line, a = source (empty when it's a plain idea).
window.CUT_QUOTES=[
  {k:'Memento mori',t:'You are going to die. Not in theory. That is what makes today count.',a:'Stoic practice'},
  {k:'Memento mori',t:'Perform each act of your life as though it were your last.',a:'Marcus Aurelius'},
  {k:'Amor fati',t:'Love your fate. The plateau, the craving, the hard morning: all of it is the material.',a:'after Nietzsche'},
  {k:'The shortness of life',t:'It is not that we have a short time to live, but that we waste a lot of it.',a:'Seneca'},
  {k:'Self-mastery',t:'No man is free who is not master of himself.',a:'Epictetus'},
  {k:'The why',t:'He who has a why to live can bear almost any how.',a:'Nietzsche'},
  {k:'Imagined suffering',t:'We suffer more often in imagination than in reality.',a:'Seneca'},
  {k:'The obstacle',t:'What stands in the way becomes the way.',a:'after Marcus Aurelius'},
  {k:'Rising',t:'When you rise unwillingly, remember: you are rising to do the work of a human being.',a:'Marcus Aurelius'},
  {k:'Eternal recurrence',t:'Would you live this exact day again, forever? Then make it one worth repeating.',a:'after Nietzsche'},
  {k:'The river',t:'No man ever steps in the same river twice. You are not the same man as yesterday. Make sure of it.',a:'after Heraclitus'},
  {k:'Ozymandias',t:'Look on my works, ye Mighty, and despair. Everything built crumbles. Build anyway.',a:'after Shelley'},
  {k:'Tempus fugit',t:'Time flies. It does not wait for motivation to show up.',a:'Virgil'},
  {k:'Carpe diem',t:'Seize the day, and trust as little as possible in tomorrow.',a:'Horace'},
  {k:'The examined life',t:'The unexamined life is not worth living. Look at the numbers. They do not lie to you.',a:'after Socrates'},
  {k:'Dust',t:'For dust thou art, and unto dust shalt thou return. Until then, move.',a:'Genesis 3:19'},
  {k:'Sisyphus',t:'The boulder rolls back down every day. Push it anyway. The pushing is the point.',a:'after Camus'},
  {k:'Premeditatio malorum',t:'Picture the bad weekend before it happens. A danger you foresaw has already lost half its power.',a:'Stoic practice'},
  {k:'Discomfort',t:'Hunger is information, not an emergency. You have survived every craving you have ever had.',a:''},
  {k:'Hara hachi bu',t:'Eat until you are eight parts full. Stop before the body asks you to.',a:'Okinawan saying'},
  {k:'Kaizen',t:'One percent better, compounded. Nobody notices the first month. Everybody notices the sixth.',a:''},
  {k:'Vanitas',t:'Your body is borrowed. One day you will give it back. Return it in better shape than you got it.',a:''},
  {k:'The youngest you',t:'Today is the youngest you will ever be again. Act like you know it.',a:''},
  {k:'Discipline',t:'First say to yourself what you would be; then do what you have to do.',a:'Epictetus'},
  {k:'Know thyself',t:'You already know which days you slip. Knowing it and planning for it are not the same thing.',a:'after the Oracle at Delphi'},
  {k:'Mono no aware',t:'Everything is passing. That is not a reason for sadness. It is a reason for attention.',a:'Japanese concept'},
  {k:'Becoming',t:'Become who you are.',a:'Pindar'},
  {k:'The long view',t:'Life can only be understood backwards; but it must be lived forwards.',a:'Kierkegaard'},
  {k:'The abyss',t:'Nobody is coming to save you. That is not bleak. It means the power was always yours.',a:''},
  {k:'Duty',t:'The plan does not care how you feel today. That is exactly why it works.',a:''},
];
